MAIN_CLASS := nameSorter.jar
REF_ID := $$(ps aux | grep $(MAIN_CLASS) | grep -v grep | awk '{print $$2}')
DEV_RELEASE := 1.0.0-SNAPSHOT
VER_RELEASE := 1.0.0

#####################################
.PHONY: compile verify test package

compile:
	@echo "Compiling..."
	@mvn compile

verify:
	@echo "Verifying..."
	@mvn verify

test:
	@echo "Running MAIN..."
	@java -jar $(MAIN_CLASS) &
	@mvn test
	@kill -9 $(REF_ID)

package:
	@echo "Packaging..."
	@mvn clean package

ver-release:
	@echo "Source base version 1.0.0 released"
	@sed -i 's|$(DEV_RELEASE)|$(VER_RELEASE)|' pom.xml

dev-release:
	@echo "Source base version 1.0.0 released"
	@sed -i 's|$(VER_RELEASE)|$(DEV_RELEASE)|' pom.xml
